use pandas.Dataframe to normalize highlights (#92)

diff --git a/scripts/ci/check_notebook_output b/scripts/ci/check_notebook_output
--- a/scripts/ci/check_notebook_output
+++ b/scripts/ci/check_notebook_output
@@ -1,3 +1,7 @@
 #!/bin/bash
 
 git ls-files "*.ipynb" | xargs -I{} python ./scripts/ci/clear_outputs_and_widgets.py {}
+if [ $? -ne 0 ]; then
+  echo -e "\033[91mError: notebook check failed\033[0m" >&2
+  exit 1
+fi
